export enum Routes {
  HOME = 'HOME',
  SERIE_DETAILS = 'SERIE_DETAILS',
  EPISODE_DETAILS = 'EPISODE_DETAILS',
}

export enum Tabs {
  SERIES = 'SERIES',
  FAVORITES = 'FAVORITES',
  PEOPLE = 'PEOPLE',
  SETTINGS = 'SETTINGS',
}
